### ISSUE TITLE
Python uWSGI hang during worker restart on recent Python version

### ISSUE THREAD

**Issue by PierreF** [unbit/uwsgi#2480]
We have an hard to reproduce issue with our uWSGI on production that fail to restart. I've found a way to produce similar bug (hopefully the exact same bug) and do some search on the cause

# Our issue on production

Relevant uWSGI options:
```
[uwsgi]
http=0.0.0.0:8080
module=bleemeo.wsgi:application
master=True
processes = 2
threads = 8
max-worker-lifetime = 3600           ; Restart workers after this many seconds
```

The issue happen on Ubuntu 22.04 (amd64) + Python 3.10.4. Sometime when worker lifetime is reached, the worker fail to stop and hang forever. Once the 2nd worker also fail the whole uWSGI stop processing requests.

 This issue does not happen on Ubuntu 20.04 + Python 3.8.10 or Python 3.9.5.

When the hang occur:
* Log say `worker 1 lifetime reached, it was running for 3601 second(s)`
* Log does NOT say `Respawned uWSGI worker 1 (new pid: 5643)`
* The worker only have one thread remaining:
```
$ ps -L wup 23
USER         PID     LWP %CPU NLWP %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
daemon        23      23  0.0    1  3.6 1062012 284748 ?      S    Aug17   0:16 uWSGI worker 1
```
* The stacktrace of the worker is the following:
```
*** backtrace of 23 ***
uWSGI worker 1(uwsgi_backtrace+0x33) [0x55d8f3241953]
uWSGI worker 1(what_i_am_doing+0x2d) [0x55d8f3241a9d]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fc9ae7a5520]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x91195) [0x7fc9ae7f4195]
/usr/lib/x86_64-linux-gnu/libc.so.6(pthread_cond_wait+0x211) [0x7fc9ae7f6ac1]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x1c435e) [0x7fc9aeb4f35e]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0xc3e) [0x7fc9ae9fd87e]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x1c61ff) [0x7fc9aeb511ff]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x22db80) [0x7fc9aebb8b80]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0(PyGC_Collect+0x94) [0x7fc9aebba2f4]
/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0(Py_FinalizeEx+0x16d) [0x7fc9aeb923cd]
uWSGI worker 1(uwsgi_plugins_atexit+0x71) [0x55d8f323e651]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x45495) [0x7fc9ae7a8495]
/usr/lib/x86_64-linux-gnu/libc.so.6(on_exit+0) [0x7fc9ae7a8610]
uWSGI worker 1(+0x403c5) [0x55d8f31f33c5]
uWSGI worker 1(end_me+0x2b) [0x55d8f323e69b]
uWSGI worker 1(uwsgi_ignition+0x147) [0x55d8f3241f87]
uWSGI worker 1(uwsgi_worker_run+0x272) [0x55d8f3246772]
uWSGI worker 1(uwsgi_run+0x465) [0x55d8f3246cf5]
uWSGI worker 1(+0x3cd84) [0x55d8f31efd84]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fc9ae78cd90]
/usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fc9ae78ce40]
uWSGI worker 1(_start+0x25) [0x55d8f31efdb5]
*** end of backtrace ***
```

# Closest way to reproduce the issue

I've manager to reproduce a similar issue on Linux (using Docker `docker run --name uwsgi-hang --rm -ti python:3.9.8 bash`)
```
# Create the most minimal wsgi application
cat > wsgi.py << EOF
def application(env, start_response):
    start_response('200 OK', [('Content-Type','text/html')])
    return [b"Hello World\n"]
EOF

# Install uwsgi (version 2.0.20 at time of writting, but issue also exist with current master)
pip install uwsgi

# Start uWSGI with master, 2 (or more threads) and reload on requests count
uwsgi --module wsgi:application --http 0.0.0.0:8080 --master --threads 2 --max-requests 20
```

Then on another terminal (`docker exec -ti uwsgi-hang bash` when using Docker):
```
while true; do curl http://localhost:8080;sleep 0.1;done
```

Wait for restart to occur after ~20 request, it might hang and took 60 seconds to restart (in my test, it always happen before the 4th restart, often on 1st or 2nd restart):
```
...The work of process 365094 is done. Seeya!

[ there is 60 seconds before above message and the next one ]

Fri Sep  9 17:17:23 2022 - worker 1 (pid: 365094) is taking too much time to die...NO MERCY !!!
worker 1 killed successfully (pid: 365094)
Respawned uWSGI worker 1 (new pid: 365369)
```

The difference with our actual production issue:
* We use max-requests (when production use max-worker-lifetime)
* The worker don't hang forever but only for ~60 seconds

# Analyze of the cause

Since I knew the issue occur with Python 3.9.8 and don't occur with Python 3.9.7, I've bisected Python code and found that the issue started with Python commit https://github.com/python/cpython/commit/94d19f606fa18a1c4d2faca1caf2f470a8ce6d46

Before this commit, the worker always restart quickly. From this commit and after, the worker sometime hang and took 60 seconds to restart.

I think the issue is that Py_Finalize is called from "non-main" thread (TID != PID). It's the following logs added to Py_FinalizeEx that make my think that:
```
 int
 Py_FinalizeEx(void)
 {
     int status = 0;
 
+    fprintf(stderr, "Py_FinalizeEx from %d\n", gettid());
```

and everytime the hang occur, the TID printed isn't the worker PID:
```
spawned uWSGI worker 1 (pid: 366661, cores: 2)
...The work of process 366661 is done (max requests reached (20 >= 20)). Seeya!
Py_FinalizeEx from 366661
worker 1 killed successfully (pid: 366661)
[ above restart worked, Py_FinalizeEx TID is the PID ]

Respawned uWSGI worker 1 (new pid: 366727)
...The work of process 366727 is done (max requests reached (91 >= 20)). Seeya!
Py_FinalizeEx from 366728
Fri Sep  9 17:22:58 2022 - worker 1 (pid: 366727) is taking too much time to die...NO MERCY !!!
```

I'm not 100% sure this bug is an uWSGI or Python bug. I didn't see any comment that Py_FinalizeEx must be called from a specific thread.

**Comment by PierreF** [comment]
I more and more think that the issue seen on production and the one seen with steps to reproduce the issue (using `--max-requests`) aren't the same issue.

I think with `--max-requests` the issue is because exit() is called from another thread than first thread.

But the issue we have on production (using `--max-worker-lifetime`) seem another one, because:
* Looking at code, I don't see how another thread than first could call exit() with max lifetime
* When issue occur with `max-requests`, the Linux command `ps waux -L` show that the worker has 2 threads: the first thread which is defunct (zombie) and the dead-locked thread that is doing the PyFinalize
* When issue occur on production (with `max-worker-lifetime`), the `ps waux -L` only show one thread, the first thread.

Finally I think #2484 / #1894 could totally explain the issue:
* a request start on the 2nd thread worker. This request took a lock. The lock WILL be release before request end, but not yet. The request is rather slow
* While that request is processing, the worker lifetime is reached. The first thread isn't busy and start to shutdown
* On shutdown, the first thread will call end_me() which call exit(). This terminate (abruptly - at least in a way that the lock isn't released) the request pending on 2nd worker
* During shutdown, a destructor want to take the same lock, but since it hold by a dead thread we have a deadlock.

**Comment by SteveByerly** [comment]
I believe this was fixed in #2626 which is now commit 06a22597bd419860904fae6f446d8e3b714f5afa

The fix would have shipped in [v2.0.25](https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.25.html), though the version's release notes are less explicit about the change than the commits https://github.com/unbit/uwsgi/compare/2.0.24...2.0.25

**Comment by ron8mcr** [comment]
@SteveByerly 

> I believe this was fixed in https://github.com/unbit/uwsgi/pull/2626 which is now commit https://github.com/unbit/uwsgi/commit/06a22597bd419860904fae6f446d8e3b714f5afa

Unfortunately, It is still reproduced with `uwsgi==2.0.26` and **python 3.12**.

I used the same steps as described in the 1st message of this issue, and everything worked well _(requests handled, workers restarted)_ with Python 3.11, and after update to Python 3.12 the issue started to happen.

P.S. I've found this issue after changing base docker image from `python:3.11-slim` to `python:3.12-slim`

**Comment by ron8mcr** [comment]
Actually, after further investigation it was found that issue reproduced only with following conditions:

* Python 3.12
* using of `pip install pyuwsgi`
* enabled `max-requests` and `py-tracebacker`

Here is a Dockerfile that allows to reproduce this:

```dockerfile
FROM python:3.12

RUN pip install pyuwsgi
RUN echo "def application(env, start_response):\n\tstart_response('200 OK', [('Content-Type','text/html')])\n\treturn [b'Hello World']" > app.py

CMD ["uwsgi", "--module=app:application", "--http=0.0.0.0:8080", "--master", "--processes=2", "--max-requests=2", "--py-tracebacker=tracebacks.sock"]
```

Run this image using:
`docker build --tag i2480 . && docker run --rm -p 8080:8080 i2480`

After performing ~6-8 HTTP requests, uwsgi just hangs.

But after any of the following changes:
* python 3.12 -> 3.11
* Remove py-tracebacker

The problem disappears

**Comment by xrmx** [comment]
@ron8mcr could you please try to reproduce with pyuwsgi and 3.12 using the uwsgi-2.0 branch?

**Comment by ron8mcr** [comment]
@xrmx I've cloned https://github.com/lincolnloop/pyuwsgi-wheels, updated `uwsgi` submodule to `uwsgi-2.0`, run few `make` tasks and couldn't reproduce the problem.

However, during simple installation using `pip install pyuwsgi` the problem reproduces

**Comment by xrmx** [comment]
@ron8mcr cool, thanks for checking
